theme = "jellybeans"

[editor]
line-number = "relative"
cursorline = true
mouse = true
color-modes = true
completion-trigger-len = 1
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-inlay-hints = true
